
message(STATUS "Enabling package generation...")

set(CPACK_PACKAGE_VERSION_MAJOR 1)
set(CPACK_PACKAGE_VERSION_MINOR 0)
set(CPACK_PACKAGE_VERSION_PATCH 0)

set(CPACK_STRIP_FILES ON)
set(CPACK_PACKAGE_VENDOR "Emil Gedda")
set(CPACK_PACKAGE_CONTACT "Emil Gedda <emil.gedda@emilgedda.se>")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "A library for interfacing with the DHT11/DHT22 modules")
set(CPACK_SOURCE_GENERATOR "TGZ")
set(CPACK_RESOURCE_FILE_LICENS "${PROJECT_SOURCE_DIR}/LICENSE")
set(CPACK_RESOURCE_FILE_README "${PROJECT_SOURCE_DIR}/README.md")

set(CPACK_SOURCE_IGNORE_FILES
    /.git
    /bin
    /compile_commands.json
    /.clangd
    /.gitignore
)

# DEB
set(CPACK_DEB_PACKAGE_COMPONENT ON)
set(CPACK_DEBIAN_PACKAGE_HOMEPAGE "https://github.com/EmilGedda/libdht")

# RPM
set(CPACK_RPM_PACKAGE_COMPONENT ON)
set(PACK_RPM_PACKAGE_LICENSE "Boost")

include(CPack)

set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}-${CPACK_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}" CACHE STRING "" FORCE)
