name: Build

on: [pull_request, push]

jobs:
  build:
    name: Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        buildtype: [Debug, Release, MinSizeRel]
        cxx: [clang++-9, g++-8]

    steps:

    - name: Install prerequisites
      run:  sudo apt-get -y install clang-9 g++-8 # cppcheck segfaults on iterator.cpp

    - uses: actions/checkout@v1

    - name: Generate build system
      run: CXX="${{ matrix.cxx }}" cmake -DCMAKE_BUILD_TYPE="${{ matrix.buildtype }}" .

    - name: Build
      run: cmake --build . --target gpio_test
