name: Style

on: [pull_request, push]

jobs:
  build:
    name: Ubuntu
    runs-on: ubuntu-latest

    steps:
    - name: Install prerequisites
      run:  sudo apt-get -y install iwyu clang-tidy-9 cppcheck

    - uses: actions/checkout@v1

    - name: Generate compilation database
      run: cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 .

    - name: Run clang format
      uses: DoozyX/clang-format-lint-action@v0.5
      with:
        source: 'src'

    - name: Run include what you use
      uses: EmilGedda/include-what-you-use-action@v1.0

    - name: clang-tidy
      run: find lib src inc -type f -name '*pp' -exec clang-tidy-9 '{}' +
