name: Style

on: [pull_request, push]

jobs:
  build:
    name: Ubuntu
    runs-on: ubuntu-latest

    steps:

    - name: Install prerequisites
      run:  sudo apt-get -y install iwyu clang-tidy-9 cppcheck

    - uses: actions/checkout@v1

    - name: Generate compilation database
      run: cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=1 .

    - uses: DoozyX/clang-format-lint-action@v0.5
      with:
        source: 'src'
        extensions: 'hpp,cpp'
        clangFormatVersion: 9

    - name: Include what you use
      run: |
          wget https://raw.githubusercontent.com/include-what-you-use/include-what-you-use/master/iwyu_tool.py
          OUTPUT=$(python iwyu_tool.py -o clang -p . | sed "/note: #includes\/fwd-decls are correct/d")
          if [ ! -z "$OUTPUT" ]; then
            echo "$OUTPUT"
            exit 1
          fi

    - name: clang-tidy
      run: clang-tidy-9 src/*

